# Generated by Django 2.1.5 on 2020-02-10 04:45

from django.db import migrations, models
import file.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid_file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to=file.models.upload_location)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
