# Generated by Django 2.1.5 on 2020-02-12 03:35

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(upload_to=file.models.upload_location),
        ),
    ]
