# Generated by Django 2.1.5 on 2020-02-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20200212_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='md5_sum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
