# Generated by Django 2.1.5 on 2020-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20200212_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
