# Generated by Django 2.1.5 on 2020-02-10 06:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0002_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('vendor', models.CharField(max_length=50)),
                ('uuid_bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('due', 'due'), ('past_due', 'past_due'), ('no_payment_required', 'no_payment_required')], max_length=20, verbose_name='paymentStatus')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.File')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
